# Generated by Django 4.1.6 on 2023-06-01 11:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0003_alter_message_options_rename_message_message_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="pw",
            field=models.CharField(default=0, max_length=4),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="one_one_Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                ("users", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
