# Generated by Django 4.1.6 on 2023-05-24 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mypage", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="UserProfile",),
    ]
