# Generated by Django 4.1.6 on 2023-05-25 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mypage", "0003_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="profile_picture",
            new_name="background_image",
        ),
    ]
