# Generated by Django 4.1.6 on 2023-05-28 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_profile"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="emoji",),
    ]
