# Generated by Django 4.1.6 on 2023-05-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_profile_emoji"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="emoji",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/"
            ),
        ),
    ]
