# Generated by Django 4.1.6 on 2023-05-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_profile_emoji"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile", name="emoji", field=models.CharField(max_length=255),
        ),
    ]
