# Generated by Django 4.1.6 on 2023-05-30 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_delete_profile"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="profile_image",),
    ]
