# Generated by Django 4.1.6 on 2023-05-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0002_board_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="board", name="views", field=models.IntegerField(default=0),
        ),
    ]
