# Generated by Django 4.1.6 on 2023-05-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0004_category_board_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="recruitment_period",
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
