# Generated by Django 4.1.6 on 2023-05-22 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0005_board_recruitment_period"),
    ]

    operations = [
        migrations.RemoveField(model_name="board", name="recruitment_period",),
    ]
