# Generated by Django 4.1.6 on 2023-05-23 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0006_remove_board_recruitment_period"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="recruitment_end_date",
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name="board",
            name="recruitment_start_date",
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
