# Generated by Django 4.1.6 on 2023-05-28 16:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("board", "0007_board_recruitment_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_posts", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
