# Generated by Django 4.1.6 on 2023-06-02 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0010_portfolio"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="pw",
            field=models.CharField(default=0, max_length=4),
            preserve_default=False,
        ),
    ]
